#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'robot-control','console_scripts','robot'
__requires__ = 'robot-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('robot-control', 'console_scripts', 'robot')()
    )
